site_name: requests
theme:
  name: material
  features:
    - navigation.top
    - navigation.expand

repo_name: a-poor/requests
repo_url: https://github.com/a-poor/requests

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - quick-start.md
  - Requests:
    - requests/index.md
    - requests/header-and-query.md
    - requests/path-params.md
  - understanding-responses.md
  - extras.md
  - Examples:
    - examples/index.md

